lygav_phpbbPostLike_hello_world_controller:
    path: /likepost/{post_id}
    defaults: { _controller: lygav.phpbbPostLike.controller:like }
    requirements:
            post_id: \d+
            dislike: \d+

lygav_phpbbPostLike_hello_world_controller:
    path: /unlikepost/{post_id}
    defaults: { _controller: lygav.phpbbPostLike.controller:dislike }
    requirements:
            post_id: \d+